### PR TITLE
Add .nuspec and template.json files

### PR DESCRIPTION
**Pull request by JuanCalle1606**
I have added the template.json files to allow the installation of the templates in `dotnet new`,  I have also created the .nuspec file and moved the DefaultBlazor projects to a content folder to allow the [packaging of a Nuget](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#packing-a-template-into-a-nuget-package-nupkg-file) file as a request in #2

To pack only need to run `nuget pack MudBlazor.Template.DefaultBlazor.nuspec`

In case this PR is accepted, could you publish the package in Nuget?

### CODE REVIEW

**Comment by Garderoben** [comment]
@JuanCalle1606 Yes, thank you so much, I wanted to do this for a long time but never took the time to do so.

How is this setup, will you be able to specify when you run dotnet new if you want wasm or server?

**Comment by JuanCalle1606** [comment]
After the .nupkg file is generated, you can install it with `dotnet new -i`, this will install 2 templates, that of Blazor Server and the Webassembly
mud1

Now these templates will already appear in `dotnet new --list` and can use them as well:

Blazor Server:
`dotnet new mudblazor` or `dotnet new mudblazor -n "name"`

Blazor WebAssembly:
`dotnet new mudblazorwasm` or `dotnet new mudblazorwasm -n "name"`

The .csproj file will have the name that we specify in the parameter `-n` or the name of the directory if you do not specify one, as in any other template.

**Comment by JuanCalle1606** [comment]
If you want I can change the name of the "mudblazor" template to "mudblazorserver"

**Comment by Garderoben** [comment]
@JuanCalle1606 yeah talked with mike-gh where do i change it or can you PR so its mudblazorserver

**Comment by Garderoben** [comment]
@JuanCalle1606 you have discord?

i published the nuget now but after installing with `dotnet new --install MudBlazor.Template.DefaultBlazor::1.0.0` i cant run `dotnet new mudblazorwasm
` or `dotnet new mudblazorserver`

**Pull request merged**
