### PR TITLE
UseStaticWebAssets() on webBuilder in Program.cs to prevent web asset…

### LINKED ISSUE #44: Bug: starup error when My ASPNETCORE_ENVIRONMENT is not setting to Development
## Bug desc
In our project,  we have multi environment configs, each of them has a appsettings file.for example:
- appsettings.json    (common config info for all env)
- appsettings.2020test.json  ( some special configs for 2020test env)
- appsettings.2020prod.json  ( some special configs for 2020prod env)

When I change the default ASPNETCORE_ENVIRONMENT to custom name, like "2020test" the MudBlazor got some error after start the project.
image

## My Configs
os: win11
IDE: VS2022 Version 17.0.0 Preview 4.1
local dotnet version : 5.0 latest /6.0 RC2
local MudBlazor version:   5.1.5  + lastest rc

image

-------------------------------

## How to reproduce
1. Create a startup Blazor Server project using the MudBlazor template
image

2. Open the launch setting file, change the env name from Development to a custome env
image

3. Start the server project, when the browser launch, the UI is a crazy large icon!
image

some static file was 404 when start not as a dev environment.
image

### PR DESCRIPTION
**Pull request by psijkof**
…s not being loaded in environments other than Development

### CODE REVIEW

**Comment by JonBunator** [comment]
Have you tested it? Is it working now?
What about `wasm-hosted`? Is it needed there as well?

**Comment by Garderoben** [comment]
@psijkof i just updated the templates to .NET 6 and .NET 6 style projects, is this still a  issue with them?

**Comment by psijkof** [comment]
Yes, there are still issues when the ASPNETCORE_ENVIRONMENT is set to some other value than Development.

**Comment by psijkof** [comment]
Yes, with Blazor Server there is still that issue.

We need to add a line, after creating the builder:

```
StaticWebAssetsLoader.UseStaticWebAssets(builder.Environment, builder.Configuration);
```

**Pull request closed without merging**
