### PR TITLE
Fix net8.0 Templates

### LINKED ISSUE #437: Rendering does not Work correclty in "InteractivityAuto_AlliInteractive_auth"
As soon you change to one of the Pages for the UserManagement, the rendering for the pages will not work anymore. 

For example the Counter Button or the Hamburger Button on the Drawer.

### LINKED ISSUE #453: error when use .net 8 template with interactive render auto
Steps to reproduce error:

1. install template with the command: dotnet new mudblazor --interactivity Auto
2. run the proyect
3. go to counter page
4. click on counter button
5. refresh the page
6. get the error
image

### PR DESCRIPTION
**Pull request by mikes-gh**
- Fixes https://github.com/MudBlazor/Templates/issues/453
- Fixes https://github.com/MudBlazor/Templates/issues/437
- Use the new `<MudThemingProvider />` to avoid `<MudPopoverProvider />` issues.
- Some fixes to namespaces
- Added install template, create all projects and build to pipeline
- Other minor fixes

### CODE REVIEW

**Comment by mikes-gh** [comment]
On Hold for https://github.com/MudBlazor/MudBlazor/pull/8102

**Comment by mikes-gh** [comment]
Maybe someone want to test these.
You can download the repo and run the build script which will give you a directory of projects to test.
@Garderoben

**Comment by henon** [comment]
I can confirm that the build script builds the test projects fine on windows

**Comment by henon** [comment]
Works well, tried InteractiveAuto.

This has nothing to do with this PR, but I noticed that for small screen sizes the Menu disappears entirely.
image

**Comment by mikes-gh** [comment]
Thats due to using MudDrawer.
I guess I should use MudGrid for the layout when the project is not Interative at root?

**Comment by mikes-gh** [comment]
Thanks for looking :-)

**Comment by henon** [comment]
In InteractivityAuto_AllInteractive it shows the burger menu which eventually works after a delay of 10 seconds or so

image

**Comment by henon** [comment]
I notice that in `InteractivityNone` there is no .sln file, just a csproj file.

**Comment by mikes-gh** [comment]
> I notice that in `InteractivityNone` there is no .sln file, just a csproj file.

I believe that's because you only need a solution file for multi project solution.
So if webassembly (client porject) is not required it creates just a csproj
https://github.com/MudBlazor/Templates/blob/1ffe033ab440a8228c8c93abe6dfb330cec84f1f/src/mudblazor/.template.config/template.json#L39

**Comment by mikes-gh** [comment]
@henon Thanks for your continued review.  I found the Home page description had the providers as tags in the description text which obviously caused some major issues.  I've added a fix if you would like to retest.  You will need to run the build script again after pull.

**Comment by mikes-gh** [comment]
@henon Maybe one last pass through the templates.
Be aware interactive auto does not work correctly at present.  The web socket for BSS does not open until the wasm files have been downloaded.  This manifests itself in the fact that the counter page takes a long time to become interactive. 
 Should be fixed by MS in 8.0.2

**Comment by henon** [comment]
I stumbled upon an exception on clicking the weather nav link in the `InteractivityServer` example.

```
System.InvalidOperationException: A component of type 'InteractivityServer.Components.Pages.Weather' has render mode 'InteractiveAutoRenderMode', but the required endpoints are not mapped on the server. When calling 'MapRazorComponents', add a call to 'AddInteractiveWebAssemblyRenderMode'. For example, 'builder.MapRazorComponents<...>.AddInteractiveWebAssemblyRenderMode()'
   at Microsoft.AspNetCore.Components.Endpoints.SSRRenderModeBoundary.AssertRenderModeIsConfigured[TRequiredMode](Type componentType, IComponentRenderMode specifiedMode, IComponentRenderMode[] configuredModes, String expectedCall)
   at Microsoft.AspNetCore.Components.Endpoints.SSRRenderModeBoundary.AssertRenderModeIsConfigured(HttpContext httpContext, Type componentType, IComponentRenderMode renderMode)
   at Microsoft.AspNetCore.Components.Endpoints.SSRRenderModeBoundary..ctor(HttpContext httpContext, Type componentType, IComponentRenderMode renderMode)
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.ResolveComponentForRenderMode(Type componentType, Nullable`1 parentComponentId, IComponentActivator componentActivator, IComponentRenderMode renderMode)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent component, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type rootComponentType, ParameterView parameters, Boolean waitForQuiescence)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by henon** [comment]
The weather page in `InteractivityServer_AllInteractive` works

**Comment by henon** [comment]
```
On the other hand, if you choose the "Per page/component" Interactivity Location,
it is necessary to include the
<MudPopoverProvider />
<MudDialogProvider />
<MudSnackbarProvider />

component on every interactive page.
```

This sentence should be fixed.

**Comment by mikes-gh** [comment]
> ```
> On the other hand, if you choose the "Per page/component" Interactivity Location,
> it is necessary to include the
> <MudPopoverProvider />
> <MudDialogProvider />
> <MudSnackbarProvider />
> 
> component on every interactive page.
> ```
> 
> This sentence should be fixed.

Plural for components spacing?

**Comment by mikes-gh** [comment]
Added fi

> I stumbled upon an exception on clicking the weather nav link in the `InteractivityServer` example.
> 
> ```
> System.InvalidOperationException: A component of type 'InteractivityServer.Components.Pages.Weather' has render mode 'InteractiveAutoRenderMode', but the required endpoints are not mapped on the server. When calling 'MapRazorComponents', add a call to 'AddInteractiveWebAssemblyRenderMode'. For example, 'builder.MapRazorComponents<...>.AddInteractiveWebAssemblyRenderMode()'
>    at Microsoft.AspNetCore.Components.Endpoints.SSRRenderModeBoundary.AssertRenderModeIsConfigured[TRequiredMode](Type componentType, IComponentRenderMode specifiedMode, IComponentRenderMode[] configuredModes, String expectedCall)
>    at Microsoft.AspNetCore.Components.Endpoints.SSRRenderModeBoundary.AssertRenderModeIsConfigured(HttpContext httpContext, Type componentType, IComponentRenderMode renderMode)
>    at Microsoft.AspNetCore.Components.Endpoints.SSRRenderModeBoundary..ctor(HttpContext httpContext, Type componentType, IComponentRenderMode renderMode)
>    at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.ResolveComponentForRenderMode(Type componentType, Nullable`1 parentComponentId, IComponentActivator componentActivator, IComponentRenderMode renderMode)
>    at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
>    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
>    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
>    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
>    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
>    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
>    at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
>    at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
>    at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
>    at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
>    at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
>    at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent component, ParameterView initialParameters)
>    at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type rootComponentType, ParameterView parameters, Boolean waitForQuiescence)
>    at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
>    at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
>    at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
> ```

Should be fixed now

**Comment by henon** [comment]
Btw, this is the first time I check any of the Auth examples. The `InteractivityAuto_UseMain` looks like any other example, where is the auth?

Edit: Oops I can't read. It doesn't have anything to do with auth

**Comment by mikes-gh** [comment]
> Btw, this is the first time I check any of the Auth examples. The `InteractivityAuto_UseMain` looks like any other example, where is the auth?

There is no Auth for that example.  The examples with Auth have it in the project name.

**Comment by ScarletKuro** [comment]
Can we merge this or there are still some concerns left?

**Comment by henon** [comment]
Not from my side.

**Comment by ashpetrosyan97** [comment]
Any new about this topic?

**Review by Garderoben — APPROVED** [review]

**Comment by Garderoben** [comment]
@mikes-gh should we merge it?

**Comment by mikes-gh** [comment]
We can merge its not perfect but better than current.

**Comment by ashpetrosyan97** [comment]
Thanks, so when we will able to get new version? Will you create release for this changes?

**Comment by ScarletKuro** [comment]
@Garderoben can we push the nuget ASAP?
As I understand only you can do it. @mikes-gh would be nice to do a github pipeline.

**Comment by Garderoben** [comment]
> @Garderoben can we push the nuget ASAP? As I understand only you can do it. @mikes-gh would be nice to do a github pipeline.

mike is working on it, i can do a release now

**Pull request merged**
